import os
import time
from datetime import datetime

FILE_DIR = "/app/files"
os.makedirs(FILE_DIR, exist_ok=True)

while True:
    timestamp = datetime.now().strftime("%y-%m-%dT%H-%M-%S")
    file_path = os.path.join(FILE_DIR, f"{timestamp}.html")

    with open(file_path, "w") as f:
        f.write(f"Generated by python at {timestamp}")

    files = sorted(os.listdir(FILE_DIR))
    while len(files) > 5:
        os.remove(os.path.join(FILE_DIR, files.pop(0)))

    time.sleep(60)

